### ISSUE TITLE
Need to specify OpenAPI version

### ISSUE THREAD

**Issue by alansill** [ballerina-guides/open-api-based-service#22]
**Description:**
The current documentation for OpenAPI use in Ballerina does not specify the OpenAPI version. THis matters, due to major changes between OpenAPI versions 2 and 3.

**Comment by rosensilva** [comment]
Hi @alansill,
This guide is based on the OpenAPI version 2. Please note that the version is indicated in the swagger sample:
https://github.com/ballerina-guides/open-api-based-service#basic-structure-of-petstore-swaggeropenapi-specification

**Comment by alansill** [comment]
Any plans to update to OpenAPI version 3?

**Comment by praneesha** [comment]
Updated the version via #34.
