### ISSUE TITLE
Update the BBG based on Open API 3.0

### ISSUE THREAD

**Issue by praneesha** [ballerina-guides/open-api-based-service#35]
**Description:**
This BBG is currently written based on Open API 2.0. We need to rewrite it based on Open API 3.0.

The Pet Store implementation based on Open API 3.0 can be found in [1].

[1] https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
Closing as we no longer maintain this repo.
